### ISSUE TITLE
Código copiado

### ISSUE THREAD

**Issue by leezyAFK** [arquinity/Cifra_Cesar#2]
Além de copiar um código de rede neural de um app chamado spick editor, agora copiou a tool do Jean... Mas tudo bem.

**Comment by arquinity** [comment]
Um script desse qualquer um faz amigo

**Comment by leezyAFK** [comment]
Uma coisa é fazer, outra é copiar e colar.

**Comment by leezyAFK** [comment]
Caso queira, eu envio o script do kripto-sec, você já tem histórico de copiar códigos e depois que é descoberto, tenta limpar o que fez.
